# Generated by Django 4.1.7 on 2023-02-15 10:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '任务中心', 'verbose_name_plural': '任务中心'},
        ),
        migrations.AlterModelOptions(
            name='taskschedulelog',
            options={'verbose_name': '任务日志', 'verbose_name_plural': '任务日志'},
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='callback',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_schedule.taskcallback', verbose_name='回调'),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='crontab',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Crontab表达式'),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='next_schedule_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='下次运行时间'),
        ),
    ]
