# Generated by Django 4.1.7 on 2023-02-16 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common_objects', '0002_alter_commoncategory_parent'),
        ('task_schedule', '0002_alter_task_options_alter_taskschedulelog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskschedule',
            options={'ordering': ('-priority', 'next_schedule_time'), 'verbose_name': '任务计划', 'verbose_name_plural': '任务计划'},
        ),
        migrations.AddField(
            model_name='taskcallback',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, to='common_objects.commontag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='next_schedule_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='下次运行时间'),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='period',
            field=models.PositiveIntegerField(default=60, verbose_name='周期(秒)'),
        ),
    ]
