# Generated by Django 4.1.7 on 2023-02-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_objects', '0002_alter_commoncategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
    ]
